"""initial_schema_phase1

Revision ID: 76a9c8e11d1a
Revises: 
Create Date: 2026-08-30 19:41:28.752935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '76a9c8e11d1a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('external_payment_id', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('gateway', sa.String(length=64), nullable=True),
    sa.Column('bank', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('failed', 'recovering', 'recovered', 'exhausted', 'escalated', name='transaction_status'), nullable=False),
    sa.Column('dnd_opt_out', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transactions_customer_id'), 'transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_payment_id'), 'transactions', ['external_payment_id'], unique=True)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_status_created_at', 'transactions', ['status', 'created_at'], unique=False)
    op.create_table('baseline_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('recovered', sa.Boolean(), nullable=False),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baseline_results_transaction_id'), 'baseline_results', ['transaction_id'], unique=True)
    op.create_table('classifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('root_cause_category', sa.Enum('card_declined', 'insufficient_funds', 'gateway_timeout', 'bank_downtime', 'otp_failure', 'fraud_false_positive', 'other', name='root_cause_category'), nullable=False),
    sa.Column('classifier_method', sa.Enum('rule', 'llm', name='classifier_method'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_transaction_id'), 'classifications', ['transaction_id'], unique=False)
    op.create_table('decisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.Enum('instant_retry', 'payment_link', 'update_card_prompt', 'escalate_human', 'suppress_dnd', name='action_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('auto_executed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_transaction_id'), 'decisions', ['transaction_id'], unique=False)
    op.create_table('recovery_receipts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('cost_of_intervention', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('outcome', sa.Enum('recovered', 'failed', 'escalated', 'suppressed', name='recovery_outcome'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_receipts_transaction_id'), 'recovery_receipts', ['transaction_id'], unique=True)
    op.create_table('actions_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('razorpay_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('amount_recovered', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_log_decision_id'), 'actions_log', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_actions_log_decision_id'), table_name='actions_log')
    op.drop_table('actions_log')
    op.drop_index(op.f('ix_recovery_receipts_transaction_id'), table_name='recovery_receipts')
    op.drop_table('recovery_receipts')
    op.drop_index(op.f('ix_decisions_transaction_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_classifications_transaction_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_baseline_results_transaction_id'), table_name='baseline_results')
    op.drop_table('baseline_results')
    op.drop_index('ix_transactions_status_created_at', table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_payment_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_customer_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
