"""add_reasoning_to_decision

Revision ID: 7cf15b326321
Revises: 76a9c8e11d1a
Create Date: 2026-08-30 20:13:56.886881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7cf15b326321'
down_revision: Union[str, None] = '76a9c8e11d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'reasoning')
    # ### end Alembic commands ###
